import type { jsPDF } from 'jspdf'
import type { BeadCell } from '../../engine/grid'

type DrawCoverPageOptions = {
  pdf: jsPDF
  beadGrid: BeadCell[]
  patternSize: number
  patternPages: number
  paletteName?: string
}

function hexToRgb(hex: string) {
  const normalized = hex.replace('#', '')

  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16),
  }
}

function getDifficulty(
  patternSize: number,
  colorsUsed: number,
) {
  const score =
    patternSize >= 150
      ? 5
      : patternSize >= 100
        ? 4
        : patternSize >= 58
          ? 3
          : patternSize >= 29
            ? 2
            : 1

  const colorBonus =
    colorsUsed >= 30
      ? 1
      : colorsUsed >= 20
        ? 0.5
        : 0

  return Math.min(5, Math.ceil(score + colorBonus))
}

export function drawCoverPage({
  pdf,
  beadGrid,
  patternSize,
  patternPages,
  paletteName = 'MARD 221',
}: DrawCoverPageOptions) {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  const colorsUsed = new Set(
    beadGrid.map((cell) => cell.color.id),
  ).size

  const difficulty = getDifficulty(
    patternSize,
    colorsUsed,
  )

 const difficultyText = `${difficulty} / 5`
  const margin = 18

  pdf.setFillColor(248, 250, 252)
  pdf.rect(
    0,
    0,
    pageWidth,
    pageHeight,
    'F',
  )

  pdf.setFillColor(124, 58, 237)
  pdf.rect(
    0,
    0,
    pageWidth,
    42,
    'F',
  )

 pdf.setTextColor(255, 255, 255)

pdf.setFont('helvetica', 'bold')
pdf.setFontSize(24)
pdf.text(
  'BEADS STUDIO',
  pageWidth / 2,
  17,
  { align: 'center' },
)

pdf.setFont('helvetica', 'normal')
pdf.setFontSize(11)
pdf.text(
  'Professional Bead Pattern',
  pageWidth / 2,
  29,
  { align: 'center' },
)
  const previewSize = 108
  const previewX = (pageWidth - previewSize) / 2
  const previewY = 53
  const cellSize = previewSize / patternSize

  pdf.setFillColor(255, 255, 255)
  pdf.setDrawColor(203, 213, 225)
  pdf.setLineWidth(0.6)

  pdf.roundedRect(
    previewX - 4,
    previewY - 4,
    previewSize + 8,
    previewSize + 8,
    4,
    4,
    'FD',
  )

  for (const cell of beadGrid) {
    const color = hexToRgb(cell.color.hex)

    pdf.setFillColor(
      color.r,
      color.g,
      color.b,
    )

    pdf.rect(
      previewX + cell.x * cellSize,
      previewY + cell.y * cellSize,
      cellSize,
      cellSize,
      'F',
    )
  }

  pdf.setDrawColor(71, 85, 105)
  pdf.setLineWidth(0.5)

  pdf.rect(
    previewX,
    previewY,
    previewSize,
    previewSize,
  )

  const cardY = previewY + previewSize + 17
  const cardWidth =
    pageWidth - margin * 2
  const cardHeight = 72

  pdf.setFillColor(255, 255, 255)
  pdf.setDrawColor(226, 232, 240)

  pdf.roundedRect(
    margin,
    cardY,
    cardWidth,
    cardHeight,
    4,
    4,
    'FD',
  )

  const leftX = margin + 10
  const rightX = pageWidth / 2 + 8

  pdf.setTextColor(100, 116, 139)
  pdf.setFontSize(9)

  pdf.text(
    'PATTERN SIZE',
    leftX,
    cardY + 12,
  )

  pdf.text(
    'TOTAL BEADS',
    rightX,
    cardY + 12,
  )

  pdf.text(
    'COLORS USED',
    leftX,
    cardY + 35,
  )

  pdf.text(
    'PATTERN PAGES',
    rightX,
    cardY + 35,
  )

  pdf.text(
    'PALETTE',
    leftX,
    cardY + 58,
  )

  pdf.text(
    'DIFFICULTY',
    rightX,
    cardY + 58,
  )

  pdf.setTextColor(30, 41, 59)
  pdf.setFontSize(15)

  pdf.text(
    `${patternSize} x ${patternSize}`,
    leftX,
    cardY + 21,
  )

  pdf.text(
    beadGrid.length.toLocaleString(),
    rightX,
    cardY + 21,
  )

  pdf.text(
    `${colorsUsed}`,
    leftX,
    cardY + 44,
  )

  pdf.text(
    `${patternPages}`,
    rightX,
    cardY + 44,
  )

  pdf.setFontSize(12)

  pdf.text(
    paletteName,
    leftX,
    cardY + 67,
  )

  pdf.text(
    difficultyText,
    rightX,
    cardY + 67,
  )

  pdf.setTextColor(100, 116, 139)
  pdf.setFontSize(9)

  pdf.text(
    'Generated by Beads Studio',
    pageWidth / 2,
    pageHeight - 14,
    { align: 'center' },
  )
}