import type { jsPDF } from 'jspdf'
import type { BeadCell } from '../../engine/grid'

type DrawCoverPageOptions = {
  pdf: jsPDF
  beadGrid: BeadCell[]
  patternSize: number
  patternPages: number
  paletteName?: string
}

function hexToRgb(hex: string) {
  const normalized = hex.replace('#', '')

  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16),
  }
}

export function drawCoverPage({
  pdf,
  beadGrid,
  patternSize,
  patternPages,
  paletteName = 'MARD 221',
}: DrawCoverPageOptions) {
  const pageWidth = pdf.internal.pageSize.getWidth()

  const colorsUsed = new Set(
    beadGrid.map((cell) => cell.color.id),
  ).size

  pdf.setTextColor(31, 41, 55)
  pdf.setFontSize(28)
  pdf.text(
    'Beads Studio',
    pageWidth / 2,
    28,
    { align: 'center' },
  )

  pdf.setFontSize(14)
  pdf.setTextColor(107, 114, 128)
  pdf.text(
    'Printable Bead Pattern',
    pageWidth / 2,
    38,
    { align: 'center' },
  )

  const previewSize = 110
  const previewX = (pageWidth - previewSize) / 2
  const previewY = 55
  const cellSize = previewSize / patternSize

  pdf.setFillColor(255, 255, 255)
  pdf.setDrawColor(156, 163, 175)
  pdf.rect(
    previewX,
    previewY,
    previewSize,
    previewSize,
    'FD',
  )

  for (const cell of beadGrid) {
    const color = hexToRgb(cell.color.hex)

    pdf.setFillColor(
      color.r,
      color.g,
      color.b,
    )

    pdf.rect(
      previewX + cell.x * cellSize,
      previewY + cell.y * cellSize,
      cellSize,
      cellSize,
      'F',
    )
  }

  pdf.setDrawColor(75, 85, 99)
  pdf.setLineWidth(0.5)
  pdf.rect(
    previewX,
    previewY,
    previewSize,
    previewSize,
  )

  const infoY = previewY + previewSize + 22

  pdf.setTextColor(31, 41, 55)
  pdf.setFontSize(13)

  pdf.text(
    `Pattern size: ${patternSize} x ${patternSize}`,
    pageWidth / 2,
    infoY,
    { align: 'center' },
  )

  pdf.text(
    `Total beads: ${beadGrid.length}`,
    pageWidth / 2,
    infoY + 10,
    { align: 'center' },
  )

  pdf.text(
    `Colors used: ${colorsUsed}`,
    pageWidth / 2,
    infoY + 20,
    { align: 'center' },
  )

  pdf.text(
    `Pattern pages: ${patternPages}`,
    pageWidth / 2,
    infoY + 30,
    { align: 'center' },
  )

  pdf.text(
    `Palette: ${paletteName}`,
    pageWidth / 2,
    infoY + 40,
    { align: 'center' },
  )

  pdf.setFontSize(9)
  pdf.setTextColor(107, 114, 128)
  pdf.text(
    'Generated by Beads Studio',
    pageWidth / 2,
    282,
    { align: 'center' },
  )
}